version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: 
          name: Install FE Deps
          command: yarn install    
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - save_cache:
          paths:
            - cms/node_modules
          key: cms-dependencies-{{ checksum "cms/yarn.lock" }}
      - run:
          name: Build Preview
          command: CI="" yarn build
      - run: 
          name: Create Preview Link
          command: bash <(curl -s https://peek.run/ci)
workflows:
    build:
      jobs:
        - build
